
project_id = "jhfzugtgazuagqfpsuku"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[edge_functions.get_profile_by_id]
verify_jwt = true
