// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhfzugtgazuagqfpsuku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZnp1Z3RnYXp1YWdxZnBzdWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDIzMDgsImV4cCI6MjA1OTExODMwOH0.gHrSHgzxm_bJd1zQTU190yZCgbz6uLy8q2kjoEqdDrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);